// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MinCreddyVersion string                 `protobuf:"bytes,4,opt,name=min_creddy_version,json=minCreddyVersion,proto3" json:"min_creddy_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InfoResponse) GetMinCreddyVersion() string {
	if x != nil {
		return x.MinCreddyVersion
	}
	return ""
}

type ScopesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopesRequest) Reset() {
	*x = ScopesRequest{}
	mi := &file_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopesRequest) ProtoMessage() {}

func (x *ScopesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopesRequest.ProtoReflect.Descriptor instead.
func (*ScopesRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{2}
}

type ScopeSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Examples      []string               `protobuf:"bytes,3,rep,name=examples,proto3" json:"examples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeSpec) Reset() {
	*x = ScopeSpec{}
	mi := &file_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeSpec) ProtoMessage() {}

func (x *ScopeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeSpec.ProtoReflect.Descriptor instead.
func (*ScopeSpec) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ScopeSpec) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *ScopeSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScopeSpec) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

type ScopesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scopes        []*ScopeSpec           `protobuf:"bytes,1,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopesResponse) Reset() {
	*x = ScopesResponse{}
	mi := &file_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopesResponse) ProtoMessage() {}

func (x *ScopesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopesResponse.ProtoReflect.Descriptor instead.
func (*ScopesResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ScopesResponse) GetScopes() []*ScopeSpec {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type ConfigSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchemaRequest) Reset() {
	*x = ConfigSchemaRequest{}
	mi := &file_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchemaRequest) ProtoMessage() {}

func (x *ConfigSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchemaRequest.ProtoReflect.Descriptor instead.
func (*ConfigSchemaRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{5}
}

type ConfigField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "string", "int", "bool", "file"
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	Default       string                 `protobuf:"bytes,5,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigField) Reset() {
	*x = ConfigField{}
	mi := &file_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigField) ProtoMessage() {}

func (x *ConfigField) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigField.ProtoReflect.Descriptor instead.
func (*ConfigField) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigField) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

type ConfigSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*ConfigField         `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchemaResponse) Reset() {
	*x = ConfigSchemaResponse{}
	mi := &file_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchemaResponse) ProtoMessage() {}

func (x *ConfigSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchemaResponse.ProtoReflect.Descriptor instead.
func (*ConfigSchemaResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigSchemaResponse) GetFields() []*ConfigField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ConstraintsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConstraintsRequest) Reset() {
	*x = ConstraintsRequest{}
	mi := &file_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConstraintsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstraintsRequest) ProtoMessage() {}

func (x *ConstraintsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstraintsRequest.ProtoReflect.Descriptor instead.
func (*ConstraintsRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{8}
}

type ConstraintsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether constraints exist (false = no constraints, any TTL acceptable)
	HasConstraints bool `protobuf:"varint,1,opt,name=has_constraints,json=hasConstraints,proto3" json:"has_constraints,omitempty"`
	// Maximum TTL in seconds (0 = no maximum)
	MaxTtlSeconds int64 `protobuf:"varint,2,opt,name=max_ttl_seconds,json=maxTtlSeconds,proto3" json:"max_ttl_seconds,omitempty"`
	// Minimum TTL in seconds (0 = no minimum)
	MinTtlSeconds int64 `protobuf:"varint,3,opt,name=min_ttl_seconds,json=minTtlSeconds,proto3" json:"min_ttl_seconds,omitempty"`
	// Human-readable description of the constraint
	Description   string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConstraintsResponse) Reset() {
	*x = ConstraintsResponse{}
	mi := &file_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConstraintsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstraintsResponse) ProtoMessage() {}

func (x *ConstraintsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstraintsResponse.ProtoReflect.Descriptor instead.
func (*ConstraintsResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ConstraintsResponse) GetHasConstraints() bool {
	if x != nil {
		return x.HasConstraints
	}
	return false
}

func (x *ConstraintsResponse) GetMaxTtlSeconds() int64 {
	if x != nil {
		return x.MaxTtlSeconds
	}
	return 0
}

func (x *ConstraintsResponse) GetMinTtlSeconds() int64 {
	if x != nil {
		return x.MinTtlSeconds
	}
	return 0
}

func (x *ConstraintsResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_proto_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigureRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_proto_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_proto_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{12}
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_proto_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scopes        []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_proto_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type GetCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialRequest) Reset() {
	*x = GetCredentialRequest{}
	mi := &file_proto_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialRequest) ProtoMessage() {}

func (x *GetCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *GetCredentialRequest) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *GetCredentialRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetCredentialRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *GetCredentialRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type GetCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,2,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	ExternalId    string                 `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialResponse) Reset() {
	*x = GetCredentialResponse{}
	mi := &file_proto_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialResponse) ProtoMessage() {}

func (x *GetCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *GetCredentialResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetCredentialResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *GetCredentialResponse) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *GetCredentialResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetCredentialResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RevokeCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCredentialRequest) Reset() {
	*x = RevokeCredentialRequest{}
	mi := &file_proto_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCredentialRequest) ProtoMessage() {}

func (x *RevokeCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCredentialRequest.ProtoReflect.Descriptor instead.
func (*RevokeCredentialRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *RevokeCredentialRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

type RevokeCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revoked       bool                   `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCredentialResponse) Reset() {
	*x = RevokeCredentialResponse{}
	mi := &file_proto_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCredentialResponse) ProtoMessage() {}

func (x *RevokeCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCredentialResponse.ProtoReflect.Descriptor instead.
func (*RevokeCredentialResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *RevokeCredentialResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *RevokeCredentialResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MatchScopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchScopeRequest) Reset() {
	*x = MatchScopeRequest{}
	mi := &file_proto_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchScopeRequest) ProtoMessage() {}

func (x *MatchScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchScopeRequest.ProtoReflect.Descriptor instead.
func (*MatchScopeRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *MatchScopeRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type MatchScopeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       bool                   `protobuf:"varint,1,opt,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchScopeResponse) Reset() {
	*x = MatchScopeResponse{}
	mi := &file_proto_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchScopeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchScopeResponse) ProtoMessage() {}

func (x *MatchScopeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchScopeResponse.ProtoReflect.Descriptor instead.
func (*MatchScopeResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *MatchScopeResponse) GetMatches() bool {
	if x != nil {
		return x.Matches
	}
	return false
}

var File_proto_plugin_proto protoreflect.FileDescriptor

const file_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x12proto/plugin.proto\x12\x10creddy.plugin.v1\"\r\n" +
	"\vInfoRequest\"\x8c\x01\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12,\n" +
	"\x12min_creddy_version\x18\x04 \x01(\tR\x10minCreddyVersion\"\x0f\n" +
	"\rScopesRequest\"c\n" +
	"\tScopeSpec\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bexamples\x18\x03 \x03(\tR\bexamples\"E\n" +
	"\x0eScopesResponse\x123\n" +
	"\x06scopes\x18\x01 \x03(\v2\x1b.creddy.plugin.v1.ScopeSpecR\x06scopes\"\x15\n" +
	"\x13ConfigSchemaRequest\"\x8d\x01\n" +
	"\vConfigField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12\x18\n" +
	"\adefault\x18\x05 \x01(\tR\adefault\"M\n" +
	"\x14ConfigSchemaResponse\x125\n" +
	"\x06fields\x18\x01 \x03(\v2\x1d.creddy.plugin.v1.ConfigFieldR\x06fields\"\x14\n" +
	"\x12ConstraintsRequest\"\xb0\x01\n" +
	"\x13ConstraintsResponse\x12'\n" +
	"\x0fhas_constraints\x18\x01 \x01(\bR\x0ehasConstraints\x12&\n" +
	"\x0fmax_ttl_seconds\x18\x02 \x01(\x03R\rmaxTtlSeconds\x12&\n" +
	"\x0fmin_ttl_seconds\x18\x03 \x01(\x03R\rminTtlSeconds\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"3\n" +
	"\x10ConfigureRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\")\n" +
	"\x11ConfigureResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x11\n" +
	"\x0fValidateRequest\">\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"C\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\"\x93\x02\n" +
	"\x14GetCredentialRequest\x12-\n" +
	"\x05agent\x18\x01 \x01(\v2\x17.creddy.plugin.v1.AgentR\x05agent\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\x12V\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v26.creddy.plugin.v1.GetCredentialRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x02\n" +
	"\x15GetCredentialResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12&\n" +
	"\x0fexpires_at_unix\x18\x02 \x01(\x03R\rexpiresAtUnix\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\x12Q\n" +
	"\bmetadata\x18\x04 \x03(\v25.creddy.plugin.v1.GetCredentialResponse.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x17RevokeCredentialRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\"J\n" +
	"\x18RevokeCredentialResponse\x12\x18\n" +
	"\arevoked\x18\x01 \x01(\bR\arevoked\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\")\n" +
	"\x11MatchScopeRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\".\n" +
	"\x12MatchScopeResponse\x12\x18\n" +
	"\amatches\x18\x01 \x01(\bR\amatches2\xa6\x06\n" +
	"\x06Plugin\x12E\n" +
	"\x04Info\x12\x1d.creddy.plugin.v1.InfoRequest\x1a\x1e.creddy.plugin.v1.InfoResponse\x12K\n" +
	"\x06Scopes\x12\x1f.creddy.plugin.v1.ScopesRequest\x1a .creddy.plugin.v1.ScopesResponse\x12]\n" +
	"\fConfigSchema\x12%.creddy.plugin.v1.ConfigSchemaRequest\x1a&.creddy.plugin.v1.ConfigSchemaResponse\x12Z\n" +
	"\vConstraints\x12$.creddy.plugin.v1.ConstraintsRequest\x1a%.creddy.plugin.v1.ConstraintsResponse\x12T\n" +
	"\tConfigure\x12\".creddy.plugin.v1.ConfigureRequest\x1a#.creddy.plugin.v1.ConfigureResponse\x12Q\n" +
	"\bValidate\x12!.creddy.plugin.v1.ValidateRequest\x1a\".creddy.plugin.v1.ValidateResponse\x12`\n" +
	"\rGetCredential\x12&.creddy.plugin.v1.GetCredentialRequest\x1a'.creddy.plugin.v1.GetCredentialResponse\x12i\n" +
	"\x10RevokeCredential\x12).creddy.plugin.v1.RevokeCredentialRequest\x1a*.creddy.plugin.v1.RevokeCredentialResponse\x12W\n" +
	"\n" +
	"MatchScope\x12#.creddy.plugin.v1.MatchScopeRequest\x1a$.creddy.plugin.v1.MatchScopeResponseB.Z,github.com/getcreddy/creddy-plugin-sdk/protob\x06proto3"

var (
	file_proto_plugin_proto_rawDescOnce sync.Once
	file_proto_plugin_proto_rawDescData []byte
)

func file_proto_plugin_proto_rawDescGZIP() []byte {
	file_proto_plugin_proto_rawDescOnce.Do(func() {
		file_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_proto_rawDesc), len(file_proto_plugin_proto_rawDesc)))
	})
	return file_proto_plugin_proto_rawDescData
}

var file_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_plugin_proto_goTypes = []any{
	(*InfoRequest)(nil),              // 0: creddy.plugin.v1.InfoRequest
	(*InfoResponse)(nil),             // 1: creddy.plugin.v1.InfoResponse
	(*ScopesRequest)(nil),            // 2: creddy.plugin.v1.ScopesRequest
	(*ScopeSpec)(nil),                // 3: creddy.plugin.v1.ScopeSpec
	(*ScopesResponse)(nil),           // 4: creddy.plugin.v1.ScopesResponse
	(*ConfigSchemaRequest)(nil),      // 5: creddy.plugin.v1.ConfigSchemaRequest
	(*ConfigField)(nil),              // 6: creddy.plugin.v1.ConfigField
	(*ConfigSchemaResponse)(nil),     // 7: creddy.plugin.v1.ConfigSchemaResponse
	(*ConstraintsRequest)(nil),       // 8: creddy.plugin.v1.ConstraintsRequest
	(*ConstraintsResponse)(nil),      // 9: creddy.plugin.v1.ConstraintsResponse
	(*ConfigureRequest)(nil),         // 10: creddy.plugin.v1.ConfigureRequest
	(*ConfigureResponse)(nil),        // 11: creddy.plugin.v1.ConfigureResponse
	(*ValidateRequest)(nil),          // 12: creddy.plugin.v1.ValidateRequest
	(*ValidateResponse)(nil),         // 13: creddy.plugin.v1.ValidateResponse
	(*Agent)(nil),                    // 14: creddy.plugin.v1.Agent
	(*GetCredentialRequest)(nil),     // 15: creddy.plugin.v1.GetCredentialRequest
	(*GetCredentialResponse)(nil),    // 16: creddy.plugin.v1.GetCredentialResponse
	(*RevokeCredentialRequest)(nil),  // 17: creddy.plugin.v1.RevokeCredentialRequest
	(*RevokeCredentialResponse)(nil), // 18: creddy.plugin.v1.RevokeCredentialResponse
	(*MatchScopeRequest)(nil),        // 19: creddy.plugin.v1.MatchScopeRequest
	(*MatchScopeResponse)(nil),       // 20: creddy.plugin.v1.MatchScopeResponse
	nil,                              // 21: creddy.plugin.v1.GetCredentialRequest.ParametersEntry
	nil,                              // 22: creddy.plugin.v1.GetCredentialResponse.MetadataEntry
}
var file_proto_plugin_proto_depIdxs = []int32{
	3,  // 0: creddy.plugin.v1.ScopesResponse.scopes:type_name -> creddy.plugin.v1.ScopeSpec
	6,  // 1: creddy.plugin.v1.ConfigSchemaResponse.fields:type_name -> creddy.plugin.v1.ConfigField
	14, // 2: creddy.plugin.v1.GetCredentialRequest.agent:type_name -> creddy.plugin.v1.Agent
	21, // 3: creddy.plugin.v1.GetCredentialRequest.parameters:type_name -> creddy.plugin.v1.GetCredentialRequest.ParametersEntry
	22, // 4: creddy.plugin.v1.GetCredentialResponse.metadata:type_name -> creddy.plugin.v1.GetCredentialResponse.MetadataEntry
	0,  // 5: creddy.plugin.v1.Plugin.Info:input_type -> creddy.plugin.v1.InfoRequest
	2,  // 6: creddy.plugin.v1.Plugin.Scopes:input_type -> creddy.plugin.v1.ScopesRequest
	5,  // 7: creddy.plugin.v1.Plugin.ConfigSchema:input_type -> creddy.plugin.v1.ConfigSchemaRequest
	8,  // 8: creddy.plugin.v1.Plugin.Constraints:input_type -> creddy.plugin.v1.ConstraintsRequest
	10, // 9: creddy.plugin.v1.Plugin.Configure:input_type -> creddy.plugin.v1.ConfigureRequest
	12, // 10: creddy.plugin.v1.Plugin.Validate:input_type -> creddy.plugin.v1.ValidateRequest
	15, // 11: creddy.plugin.v1.Plugin.GetCredential:input_type -> creddy.plugin.v1.GetCredentialRequest
	17, // 12: creddy.plugin.v1.Plugin.RevokeCredential:input_type -> creddy.plugin.v1.RevokeCredentialRequest
	19, // 13: creddy.plugin.v1.Plugin.MatchScope:input_type -> creddy.plugin.v1.MatchScopeRequest
	1,  // 14: creddy.plugin.v1.Plugin.Info:output_type -> creddy.plugin.v1.InfoResponse
	4,  // 15: creddy.plugin.v1.Plugin.Scopes:output_type -> creddy.plugin.v1.ScopesResponse
	7,  // 16: creddy.plugin.v1.Plugin.ConfigSchema:output_type -> creddy.plugin.v1.ConfigSchemaResponse
	9,  // 17: creddy.plugin.v1.Plugin.Constraints:output_type -> creddy.plugin.v1.ConstraintsResponse
	11, // 18: creddy.plugin.v1.Plugin.Configure:output_type -> creddy.plugin.v1.ConfigureResponse
	13, // 19: creddy.plugin.v1.Plugin.Validate:output_type -> creddy.plugin.v1.ValidateResponse
	16, // 20: creddy.plugin.v1.Plugin.GetCredential:output_type -> creddy.plugin.v1.GetCredentialResponse
	18, // 21: creddy.plugin.v1.Plugin.RevokeCredential:output_type -> creddy.plugin.v1.RevokeCredentialResponse
	20, // 22: creddy.plugin.v1.Plugin.MatchScope:output_type -> creddy.plugin.v1.MatchScopeResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_plugin_proto_init() }
func file_proto_plugin_proto_init() {
	if File_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_proto_rawDesc), len(file_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugin_proto_goTypes,
		DependencyIndexes: file_proto_plugin_proto_depIdxs,
		MessageInfos:      file_proto_plugin_proto_msgTypes,
	}.Build()
	File_proto_plugin_proto = out.File
	file_proto_plugin_proto_goTypes = nil
	file_proto_plugin_proto_depIdxs = nil
}
